// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/wallet.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 21197574;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_hyphen_wallet',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> crateApiWalletBlake3Hash({required List<int> data});

  Future<WalletCreateResult> crateApiWalletCreateWallet();

  Future<WalletCreateResult> crateApiWalletCreateWalletWithPassword({
    required String password,
  });

  Future<WalletCreateResult> crateApiWalletCreateWalletWithWordCount({
    required int wordCount,
  });

  Future<String> crateApiWalletDecryptWallet({
    required List<int> encryptedData,
    required String password,
  });

  Future<KeyPairInfo> crateApiWalletDeriveKey({
    required String seedHex,
    required int account,
    required int change,
    required int index,
    required bool isMainnet,
  });

  Future<Uint8List> crateApiWalletEncryptWallet({
    required String mnemonic,
    required String password,
  });

  Future<String> crateApiWalletGenerateMnemonic({required int wordCount});

  Future<ChainStatusResult> crateApiWalletGetChainStatus({
    required String host,
    required int port,
  });

  Future<int> crateApiWalletGetCoinType();

  Future<String> crateApiWalletGetDefaultAddress({
    required String seedHex,
    required bool isMainnet,
  });

  Future<String> crateApiWalletGetDerivationPath({
    required int account,
    required int change,
    required int index,
  });

  Future<bool> crateApiWalletIsMainnetAddress({required String address});

  Future<String> crateApiWalletMnemonicToSeedHex({
    required String mnemonic,
    required String passphrase,
  });

  Future<String> crateApiWalletPqTransformPassword({required String password});

  Future<WalletCreateResult> crateApiWalletRestoreWallet({
    required String mnemonic,
    required String passphrase,
  });

  Future<WalletCreateResult> crateApiWalletRestoreWalletWithPassword({
    required String mnemonic,
    required String password,
  });

  Future<WalletScanResult> crateApiWalletScanWalletOutputs({
    required String host,
    required int port,
    required String seedHex,
    required int account,
    required BigInt startHeight,
    required BigInt endHeight,
    required bool isMainnet,
  });

  Future<TransactionSendResult> crateApiWalletSendTransaction({
    required String host,
    required int port,
    required String seedHex,
    required int account,
    required String recipientAddress,
    required BigInt amount,
    required BigInt fee,
    required String ownedOutputsJson,
    required int ringSize,
  });

  Future<SignResult> crateApiWalletSignMessage({
    required String seedHex,
    required int account,
    required int change,
    required int index,
    required List<int> message,
  });

  Future<bool> crateApiWalletValidateAddress({required String address});

  Future<bool> crateApiWalletValidateMnemonic({required String mnemonic});

  Future<bool> crateApiWalletVerifySignature({
    required List<int> message,
    required String ed25519SignatureHex,
    required String ed25519PublicHex,
    required String wotsSignatureHex,
    required String wotsPublicHashHex,
    required String wotsAddrSeedHex,
  });

  Future<String> crateApiWalletWalletVersion();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> crateApiWalletBlake3Hash({required List<int> data}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(data, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletBlake3HashConstMeta,
        argValues: [data],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletBlake3HashConstMeta =>
      const TaskConstMeta(debugName: "blake3_hash", argNames: ["data"]);

  @override
  Future<WalletCreateResult> crateApiWalletCreateWallet() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_create_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCreateWalletConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCreateWalletConstMeta =>
      const TaskConstMeta(debugName: "create_wallet", argNames: []);

  @override
  Future<WalletCreateResult> crateApiWalletCreateWalletWithPassword({
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_create_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCreateWalletWithPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCreateWalletWithPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "create_wallet_with_password",
        argNames: ["password"],
      );

  @override
  Future<WalletCreateResult> crateApiWalletCreateWalletWithWordCount({
    required int wordCount,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(wordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_create_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletCreateWalletWithWordCountConstMeta,
        argValues: [wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletCreateWalletWithWordCountConstMeta =>
      const TaskConstMeta(
        debugName: "create_wallet_with_word_count",
        argNames: ["wordCount"],
      );

  @override
  Future<String> crateApiWalletDecryptWallet({
    required List<int> encryptedData,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(encryptedData, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletDecryptWalletConstMeta,
        argValues: [encryptedData, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletDecryptWalletConstMeta =>
      const TaskConstMeta(
        debugName: "decrypt_wallet",
        argNames: ["encryptedData", "password"],
      );

  @override
  Future<KeyPairInfo> crateApiWalletDeriveKey({
    required String seedHex,
    required int account,
    required int change,
    required int index,
    required bool isMainnet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedHex, serializer);
          sse_encode_u_32(account, serializer);
          sse_encode_u_32(change, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_bool(isMainnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_key_pair_info,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletDeriveKeyConstMeta,
        argValues: [seedHex, account, change, index, isMainnet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletDeriveKeyConstMeta => const TaskConstMeta(
    debugName: "derive_key",
    argNames: ["seedHex", "account", "change", "index", "isMainnet"],
  );

  @override
  Future<Uint8List> crateApiWalletEncryptWallet({
    required String mnemonic,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletEncryptWalletConstMeta,
        argValues: [mnemonic, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletEncryptWalletConstMeta =>
      const TaskConstMeta(
        debugName: "encrypt_wallet",
        argNames: ["mnemonic", "password"],
      );

  @override
  Future<String> crateApiWalletGenerateMnemonic({required int wordCount}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_8(wordCount, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGenerateMnemonicConstMeta,
        argValues: [wordCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGenerateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "generate_mnemonic",
        argNames: ["wordCount"],
      );

  @override
  Future<ChainStatusResult> crateApiWalletGetChainStatus({
    required String host,
    required int port,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_chain_status_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetChainStatusConstMeta,
        argValues: [host, port],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetChainStatusConstMeta =>
      const TaskConstMeta(
        debugName: "get_chain_status",
        argNames: ["host", "port"],
      );

  @override
  Future<int> crateApiWalletGetCoinType() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_u_32,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletGetCoinTypeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetCoinTypeConstMeta =>
      const TaskConstMeta(debugName: "get_coin_type", argNames: []);

  @override
  Future<String> crateApiWalletGetDefaultAddress({
    required String seedHex,
    required bool isMainnet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedHex, serializer);
          sse_encode_bool(isMainnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletGetDefaultAddressConstMeta,
        argValues: [seedHex, isMainnet],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetDefaultAddressConstMeta =>
      const TaskConstMeta(
        debugName: "get_default_address",
        argNames: ["seedHex", "isMainnet"],
      );

  @override
  Future<String> crateApiWalletGetDerivationPath({
    required int account,
    required int change,
    required int index,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_32(account, serializer);
          sse_encode_u_32(change, serializer);
          sse_encode_u_32(index, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletGetDerivationPathConstMeta,
        argValues: [account, change, index],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletGetDerivationPathConstMeta =>
      const TaskConstMeta(
        debugName: "get_derivation_path",
        argNames: ["account", "change", "index"],
      );

  @override
  Future<bool> crateApiWalletIsMainnetAddress({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletIsMainnetAddressConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletIsMainnetAddressConstMeta =>
      const TaskConstMeta(
        debugName: "is_mainnet_address",
        argNames: ["address"],
      );

  @override
  Future<String> crateApiWalletMnemonicToSeedHex({
    required String mnemonic,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletMnemonicToSeedHexConstMeta,
        argValues: [mnemonic, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletMnemonicToSeedHexConstMeta =>
      const TaskConstMeta(
        debugName: "mnemonic_to_seed_hex",
        argNames: ["mnemonic", "passphrase"],
      );

  @override
  Future<String> crateApiWalletPqTransformPassword({required String password}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletPqTransformPasswordConstMeta,
        argValues: [password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletPqTransformPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "pq_transform_password",
        argNames: ["password"],
      );

  @override
  Future<WalletCreateResult> crateApiWalletRestoreWallet({
    required String mnemonic,
    required String passphrase,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(passphrase, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_create_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletRestoreWalletConstMeta,
        argValues: [mnemonic, passphrase],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletRestoreWalletConstMeta =>
      const TaskConstMeta(
        debugName: "restore_wallet",
        argNames: ["mnemonic", "passphrase"],
      );

  @override
  Future<WalletCreateResult> crateApiWalletRestoreWalletWithPassword({
    required String mnemonic,
    required String password,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          sse_encode_String(password, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_create_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletRestoreWalletWithPasswordConstMeta,
        argValues: [mnemonic, password],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletRestoreWalletWithPasswordConstMeta =>
      const TaskConstMeta(
        debugName: "restore_wallet_with_password",
        argNames: ["mnemonic", "password"],
      );

  @override
  Future<WalletScanResult> crateApiWalletScanWalletOutputs({
    required String host,
    required int port,
    required String seedHex,
    required int account,
    required BigInt startHeight,
    required BigInt endHeight,
    required bool isMainnet,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(seedHex, serializer);
          sse_encode_u_32(account, serializer);
          sse_encode_u_64(startHeight, serializer);
          sse_encode_u_64(endHeight, serializer);
          sse_encode_bool(isMainnet, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_wallet_scan_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletScanWalletOutputsConstMeta,
        argValues: [
          host,
          port,
          seedHex,
          account,
          startHeight,
          endHeight,
          isMainnet,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletScanWalletOutputsConstMeta =>
      const TaskConstMeta(
        debugName: "scan_wallet_outputs",
        argNames: [
          "host",
          "port",
          "seedHex",
          "account",
          "startHeight",
          "endHeight",
          "isMainnet",
        ],
      );

  @override
  Future<TransactionSendResult> crateApiWalletSendTransaction({
    required String host,
    required int port,
    required String seedHex,
    required int account,
    required String recipientAddress,
    required BigInt amount,
    required BigInt fee,
    required String ownedOutputsJson,
    required int ringSize,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(host, serializer);
          sse_encode_u_16(port, serializer);
          sse_encode_String(seedHex, serializer);
          sse_encode_u_32(account, serializer);
          sse_encode_String(recipientAddress, serializer);
          sse_encode_u_64(amount, serializer);
          sse_encode_u_64(fee, serializer);
          sse_encode_String(ownedOutputsJson, serializer);
          sse_encode_u_32(ringSize, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 19,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_transaction_send_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletSendTransactionConstMeta,
        argValues: [
          host,
          port,
          seedHex,
          account,
          recipientAddress,
          amount,
          fee,
          ownedOutputsJson,
          ringSize,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSendTransactionConstMeta =>
      const TaskConstMeta(
        debugName: "send_transaction",
        argNames: [
          "host",
          "port",
          "seedHex",
          "account",
          "recipientAddress",
          "amount",
          "fee",
          "ownedOutputsJson",
          "ringSize",
        ],
      );

  @override
  Future<SignResult> crateApiWalletSignMessage({
    required String seedHex,
    required int account,
    required int change,
    required int index,
    required List<int> message,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(seedHex, serializer);
          sse_encode_u_32(account, serializer);
          sse_encode_u_32(change, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_list_prim_u_8_loose(message, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sign_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletSignMessageConstMeta,
        argValues: [seedHex, account, change, index, message],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletSignMessageConstMeta => const TaskConstMeta(
    debugName: "sign_message",
    argNames: ["seedHex", "account", "change", "index", "message"],
  );

  @override
  Future<bool> crateApiWalletValidateAddress({required String address}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 21,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletValidateAddressConstMeta,
        argValues: [address],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletValidateAddressConstMeta =>
      const TaskConstMeta(debugName: "validate_address", argNames: ["address"]);

  @override
  Future<bool> crateApiWalletValidateMnemonic({required String mnemonic}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(mnemonic, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletValidateMnemonicConstMeta,
        argValues: [mnemonic],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletValidateMnemonicConstMeta =>
      const TaskConstMeta(
        debugName: "validate_mnemonic",
        argNames: ["mnemonic"],
      );

  @override
  Future<bool> crateApiWalletVerifySignature({
    required List<int> message,
    required String ed25519SignatureHex,
    required String ed25519PublicHex,
    required String wotsSignatureHex,
    required String wotsPublicHashHex,
    required String wotsAddrSeedHex,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(message, serializer);
          sse_encode_String(ed25519SignatureHex, serializer);
          sse_encode_String(ed25519PublicHex, serializer);
          sse_encode_String(wotsSignatureHex, serializer);
          sse_encode_String(wotsPublicHashHex, serializer);
          sse_encode_String(wotsAddrSeedHex, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiWalletVerifySignatureConstMeta,
        argValues: [
          message,
          ed25519SignatureHex,
          ed25519PublicHex,
          wotsSignatureHex,
          wotsPublicHashHex,
          wotsAddrSeedHex,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletVerifySignatureConstMeta =>
      const TaskConstMeta(
        debugName: "verify_signature",
        argNames: [
          "message",
          "ed25519SignatureHex",
          "ed25519PublicHex",
          "wotsSignatureHex",
          "wotsPublicHashHex",
          "wotsAddrSeedHex",
        ],
      );

  @override
  Future<String> crateApiWalletWalletVersion() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiWalletWalletVersionConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiWalletWalletVersionConstMeta =>
      const TaskConstMeta(debugName: "wallet_version", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  ChainStatusResult dco_decode_chain_status_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ChainStatusResult(
      height: dco_decode_u_64(arr[0]),
      totalOutputs: dco_decode_u_64(arr[1]),
      tipHashHex: dco_decode_String(arr[2]),
    );
  }

  @protected
  KeyPairInfo dco_decode_key_pair_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return KeyPairInfo(
      address: dco_decode_String(arr[0]),
      viewPublicHex: dco_decode_String(arr[1]),
      spendPublicHex: dco_decode_String(arr[2]),
      ed25519PublicHex: dco_decode_String(arr[3]),
      wotsPublicHashHex: dco_decode_String(arr[4]),
    );
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  SignResult dco_decode_sign_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SignResult(
      ed25519SignatureHex: dco_decode_String(arr[0]),
      ed25519PublicHex: dco_decode_String(arr[1]),
      wotsSignatureHex: dco_decode_String(arr[2]),
      wotsPublicHashHex: dco_decode_String(arr[3]),
      wotsAddrSeedHex: dco_decode_String(arr[4]),
    );
  }

  @protected
  TransactionSendResult dco_decode_transaction_send_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return TransactionSendResult(
      txHashHex: dco_decode_String(arr[0]),
      accepted: dco_decode_bool(arr[1]),
      errorMessage: dco_decode_String(arr[2]),
      spentIndicesCsv: dco_decode_String(arr[3]),
      vreUsedAdaptive: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  WalletCreateResult dco_decode_wallet_create_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return WalletCreateResult(
      mnemonic: dco_decode_String(arr[0]),
      seedHex: dco_decode_String(arr[1]),
      addressMainnet: dco_decode_String(arr[2]),
      addressTestnet: dco_decode_String(arr[3]),
      viewPublicHex: dco_decode_String(arr[4]),
      spendPublicHex: dco_decode_String(arr[5]),
    );
  }

  @protected
  WalletScanResult dco_decode_wallet_scan_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return WalletScanResult(
      totalBalance: dco_decode_u_64(arr[0]),
      outputCount: dco_decode_u_64(arr[1]),
      scannedHeight: dco_decode_u_64(arr[2]),
      outputsJson: dco_decode_String(arr[3]),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  ChainStatusResult sse_decode_chain_status_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_height = sse_decode_u_64(deserializer);
    var var_totalOutputs = sse_decode_u_64(deserializer);
    var var_tipHashHex = sse_decode_String(deserializer);
    return ChainStatusResult(
      height: var_height,
      totalOutputs: var_totalOutputs,
      tipHashHex: var_tipHashHex,
    );
  }

  @protected
  KeyPairInfo sse_decode_key_pair_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_address = sse_decode_String(deserializer);
    var var_viewPublicHex = sse_decode_String(deserializer);
    var var_spendPublicHex = sse_decode_String(deserializer);
    var var_ed25519PublicHex = sse_decode_String(deserializer);
    var var_wotsPublicHashHex = sse_decode_String(deserializer);
    return KeyPairInfo(
      address: var_address,
      viewPublicHex: var_viewPublicHex,
      spendPublicHex: var_spendPublicHex,
      ed25519PublicHex: var_ed25519PublicHex,
      wotsPublicHashHex: var_wotsPublicHashHex,
    );
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  SignResult sse_decode_sign_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_ed25519SignatureHex = sse_decode_String(deserializer);
    var var_ed25519PublicHex = sse_decode_String(deserializer);
    var var_wotsSignatureHex = sse_decode_String(deserializer);
    var var_wotsPublicHashHex = sse_decode_String(deserializer);
    var var_wotsAddrSeedHex = sse_decode_String(deserializer);
    return SignResult(
      ed25519SignatureHex: var_ed25519SignatureHex,
      ed25519PublicHex: var_ed25519PublicHex,
      wotsSignatureHex: var_wotsSignatureHex,
      wotsPublicHashHex: var_wotsPublicHashHex,
      wotsAddrSeedHex: var_wotsAddrSeedHex,
    );
  }

  @protected
  TransactionSendResult sse_decode_transaction_send_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txHashHex = sse_decode_String(deserializer);
    var var_accepted = sse_decode_bool(deserializer);
    var var_errorMessage = sse_decode_String(deserializer);
    var var_spentIndicesCsv = sse_decode_String(deserializer);
    var var_vreUsedAdaptive = sse_decode_bool(deserializer);
    return TransactionSendResult(
      txHashHex: var_txHashHex,
      accepted: var_accepted,
      errorMessage: var_errorMessage,
      spentIndicesCsv: var_spentIndicesCsv,
      vreUsedAdaptive: var_vreUsedAdaptive,
    );
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  WalletCreateResult sse_decode_wallet_create_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_mnemonic = sse_decode_String(deserializer);
    var var_seedHex = sse_decode_String(deserializer);
    var var_addressMainnet = sse_decode_String(deserializer);
    var var_addressTestnet = sse_decode_String(deserializer);
    var var_viewPublicHex = sse_decode_String(deserializer);
    var var_spendPublicHex = sse_decode_String(deserializer);
    return WalletCreateResult(
      mnemonic: var_mnemonic,
      seedHex: var_seedHex,
      addressMainnet: var_addressMainnet,
      addressTestnet: var_addressTestnet,
      viewPublicHex: var_viewPublicHex,
      spendPublicHex: var_spendPublicHex,
    );
  }

  @protected
  WalletScanResult sse_decode_wallet_scan_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_totalBalance = sse_decode_u_64(deserializer);
    var var_outputCount = sse_decode_u_64(deserializer);
    var var_scannedHeight = sse_decode_u_64(deserializer);
    var var_outputsJson = sse_decode_String(deserializer);
    return WalletScanResult(
      totalBalance: var_totalBalance,
      outputCount: var_outputCount,
      scannedHeight: var_scannedHeight,
      outputsJson: var_outputsJson,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_chain_status_result(
    ChainStatusResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.height, serializer);
    sse_encode_u_64(self.totalOutputs, serializer);
    sse_encode_String(self.tipHashHex, serializer);
  }

  @protected
  void sse_encode_key_pair_info(KeyPairInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.address, serializer);
    sse_encode_String(self.viewPublicHex, serializer);
    sse_encode_String(self.spendPublicHex, serializer);
    sse_encode_String(self.ed25519PublicHex, serializer);
    sse_encode_String(self.wotsPublicHashHex, serializer);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_sign_result(SignResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.ed25519SignatureHex, serializer);
    sse_encode_String(self.ed25519PublicHex, serializer);
    sse_encode_String(self.wotsSignatureHex, serializer);
    sse_encode_String(self.wotsPublicHashHex, serializer);
    sse_encode_String(self.wotsAddrSeedHex, serializer);
  }

  @protected
  void sse_encode_transaction_send_result(
    TransactionSendResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txHashHex, serializer);
    sse_encode_bool(self.accepted, serializer);
    sse_encode_String(self.errorMessage, serializer);
    sse_encode_String(self.spentIndicesCsv, serializer);
    sse_encode_bool(self.vreUsedAdaptive, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_wallet_create_result(
    WalletCreateResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.mnemonic, serializer);
    sse_encode_String(self.seedHex, serializer);
    sse_encode_String(self.addressMainnet, serializer);
    sse_encode_String(self.addressTestnet, serializer);
    sse_encode_String(self.viewPublicHex, serializer);
    sse_encode_String(self.spendPublicHex, serializer);
  }

  @protected
  void sse_encode_wallet_scan_result(
    WalletScanResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.totalBalance, serializer);
    sse_encode_u_64(self.outputCount, serializer);
    sse_encode_u_64(self.scannedHeight, serializer);
    sse_encode_String(self.outputsJson, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
