// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `derive_wallet_key`, `wallet_from_mnemonic`, `xof_encrypt`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncryptedWallet`

/// Generate a new BIP39 mnemonic phrase.
///
/// `word_count`: 12, 15, 18, 21, or 24.
/// Returns the mnemonic as a space-separated string.
Future<String> generateMnemonic({required int wordCount}) =>
    RustLib.instance.api.crateApiWalletGenerateMnemonic(wordCount: wordCount);

/// Validate a BIP39 mnemonic phrase.
///
/// Returns true if the mnemonic is valid (correct word count, valid words,
/// correct checksum).
Future<bool> validateMnemonic({required String mnemonic}) =>
    RustLib.instance.api.crateApiWalletValidateMnemonic(mnemonic: mnemonic);

/// Create a new wallet with a fresh 24-word mnemonic.
///
/// Returns the mnemonic phrase and default account addresses.
Future<WalletCreateResult> createWallet() =>
    RustLib.instance.api.crateApiWalletCreateWallet();

/// Create a new wallet with a specific word count (12 or 24).
Future<WalletCreateResult> createWalletWithWordCount({
  required int wordCount,
}) => RustLib.instance.api.crateApiWalletCreateWalletWithWordCount(
  wordCount: wordCount,
);

/// Create a wallet with a password that is transformed through a quantum-resistant
/// algorithm before being used as the BIP39 passphrase.
///
/// The password is NOT used directly — it is first passed through WOTS+ hash chains
/// (67 chains × 15 steps of BLAKE3) to produce a quantum-hardened passphrase.
/// This ensures the derived seed is secure even against quantum computers running
/// Grover's algorithm on the BIP39 PBKDF2.
Future<WalletCreateResult> createWalletWithPassword({
  required String password,
}) => RustLib.instance.api.crateApiWalletCreateWalletWithPassword(
  password: password,
);

/// Restore a wallet from an existing BIP39 mnemonic.
///
/// `passphrase` is the optional BIP39 passphrase (empty string if not used).
/// If a password was used during creation, it must be the same password here —
/// it will be transformed through the same quantum-resistant algorithm.
Future<WalletCreateResult> restoreWallet({
  required String mnemonic,
  required String passphrase,
}) => RustLib.instance.api.crateApiWalletRestoreWallet(
  mnemonic: mnemonic,
  passphrase: passphrase,
);

/// Restore a wallet using the quantum-resistant password transformation.
///
/// The password is transformed through WOTS+ hash chains before being used
/// as the BIP39 passphrase, matching the process used during creation.
Future<WalletCreateResult> restoreWalletWithPassword({
  required String mnemonic,
  required String password,
}) => RustLib.instance.api.crateApiWalletRestoreWalletWithPassword(
  mnemonic: mnemonic,
  password: password,
);

/// Transform a raw password into a quantum-resistant passphrase using WOTS+ hash chains.
///
/// Process:
///   1. Derive a 32-byte seed from the password: BLAKE3("Hyphen_PQ_seed" || password)
///   2. Derive an addr_seed: BLAKE3("Hyphen_PQ_addr" || password)
///   3. Generate 67 WOTS+ chain secrets from the seed
///   4. Run each chain secret through 15 steps of BLAKE3 domain-separated hashing
///   5. Hash all 67 chain endpoints together to produce the final 32-byte passphrase
///   6. Hex-encode the result for use as BIP39 passphrase
///
/// Security: an adversary with a quantum computer would need to invert 67 × 15 = 1005
/// sequential BLAKE3 hash invocations per guess, nullifying Grover's quadratic speedup
/// on the individual hash chain structure.
Future<String> pqTransformPassword({required String password}) =>
    RustLib.instance.api.crateApiWalletPqTransformPassword(password: password);

/// Derive keys for a specific BIP44 path: m/44'/868'/account'/change/index.
///
/// `seed_hex` is the hex-encoded 64-byte BIP39 seed.
/// `is_mainnet` determines address format.
Future<KeyPairInfo> deriveKey({
  required String seedHex,
  required int account,
  required int change,
  required int index,
  required bool isMainnet,
}) => RustLib.instance.api.crateApiWalletDeriveKey(
  seedHex: seedHex,
  account: account,
  change: change,
  index: index,
  isMainnet: isMainnet,
);

/// Get the default address (account=0, change=0, index=0).
Future<String> getDefaultAddress({
  required String seedHex,
  required bool isMainnet,
}) => RustLib.instance.api.crateApiWalletGetDefaultAddress(
  seedHex: seedHex,
  isMainnet: isMainnet,
);

/// Get the BIP44 derivation path string for display.
Future<String> getDerivationPath({
  required int account,
  required int change,
  required int index,
}) => RustLib.instance.api.crateApiWalletGetDerivationPath(
  account: account,
  change: change,
  index: index,
);

/// Derive a seed from mnemonic (returns hex-encoded 64-byte seed).
Future<String> mnemonicToSeedHex({
  required String mnemonic,
  required String passphrase,
}) => RustLib.instance.api.crateApiWalletMnemonicToSeedHex(
  mnemonic: mnemonic,
  passphrase: passphrase,
);

/// Sign a message with hybrid quantum-resistant signature.
///
/// Uses both Ed25519 and WOTS+ to create a dual signature.
/// Even if elliptic curves are broken by quantum computers,
/// the WOTS+ signature remains secure.
Future<SignResult> signMessage({
  required String seedHex,
  required int account,
  required int change,
  required int index,
  required List<int> message,
}) => RustLib.instance.api.crateApiWalletSignMessage(
  seedHex: seedHex,
  account: account,
  change: change,
  index: index,
  message: message,
);

/// Verify a hybrid signature.
Future<bool> verifySignature({
  required List<int> message,
  required String ed25519SignatureHex,
  required String ed25519PublicHex,
  required String wotsSignatureHex,
  required String wotsPublicHashHex,
  required String wotsAddrSeedHex,
}) => RustLib.instance.api.crateApiWalletVerifySignature(
  message: message,
  ed25519SignatureHex: ed25519SignatureHex,
  ed25519PublicHex: ed25519PublicHex,
  wotsSignatureHex: wotsSignatureHex,
  wotsPublicHashHex: wotsPublicHashHex,
  wotsAddrSeedHex: wotsAddrSeedHex,
);

/// Validate a Hyphen address string.
Future<bool> validateAddress({required String address}) =>
    RustLib.instance.api.crateApiWalletValidateAddress(address: address);

/// Check if an address is mainnet.
Future<bool> isMainnetAddress({required String address}) =>
    RustLib.instance.api.crateApiWalletIsMainnetAddress(address: address);

/// Encrypt wallet data (mnemonic) with a password.
///
/// Format: [salt:32] [mac:32] [ciphertext:N]
/// KDF: 100,000 iterations of blake3
/// Cipher: blake3-XOF stream cipher
/// MAC: blake3 keyed hash (encrypt-then-MAC)
Future<Uint8List> encryptWallet({
  required String mnemonic,
  required String password,
}) => RustLib.instance.api.crateApiWalletEncryptWallet(
  mnemonic: mnemonic,
  password: password,
);

/// Decrypt wallet data with a password.
///
/// Returns the mnemonic string if the password is correct.
Future<String> decryptWallet({
  required List<int> encryptedData,
  required String password,
}) => RustLib.instance.api.crateApiWalletDecryptWallet(
  encryptedData: encryptedData,
  password: password,
);

/// Get wallet version info.
Future<String> walletVersion() =>
    RustLib.instance.api.crateApiWalletWalletVersion();

/// Get the coin type used for BIP44 derivation.
Future<int> getCoinType() => RustLib.instance.api.crateApiWalletGetCoinType();

/// Hash arbitrary data with blake3 (utility).
Future<String> blake3Hash({required List<int> data}) =>
    RustLib.instance.api.crateApiWalletBlake3Hash(data: data);

/// Query the chain status from a node.
Future<ChainStatusResult> getChainStatus({
  required String host,
  required int port,
}) => RustLib.instance.api.crateApiWalletGetChainStatus(host: host, port: port);

/// Scan the blockchain for wallet-owned outputs.
///
/// Downloads blocks from `start_height` to `end_height`, checking each
/// output against the wallet's view key. Returns owned outputs as JSON.
Future<WalletScanResult> scanWalletOutputs({
  required String host,
  required int port,
  required String seedHex,
  required int account,
  required BigInt startHeight,
  required BigInt endHeight,
  required bool isMainnet,
}) => RustLib.instance.api.crateApiWalletScanWalletOutputs(
  host: host,
  port: port,
  seedHex: seedHex,
  account: account,
  startHeight: startHeight,
  endHeight: endHeight,
  isMainnet: isMainnet,
);

/// Build and send a shielded transaction.
///
/// Selects inputs from owned outputs, fetches decoys for ring signatures,
/// constructs a CLSAG-signed transaction with range proofs, and submits
/// it to the node.
Future<TransactionSendResult> sendTransaction({
  required String host,
  required int port,
  required String seedHex,
  required int account,
  required String recipientAddress,
  required BigInt amount,
  required BigInt fee,
  required String ownedOutputsJson,
  required int ringSize,
}) => RustLib.instance.api.crateApiWalletSendTransaction(
  host: host,
  port: port,
  seedHex: seedHex,
  account: account,
  recipientAddress: recipientAddress,
  amount: amount,
  fee: fee,
  ownedOutputsJson: ownedOutputsJson,
  ringSize: ringSize,
);

/// Result of a chain status query.
class ChainStatusResult {
  final BigInt height;
  final BigInt totalOutputs;
  final String tipHashHex;

  const ChainStatusResult({
    required this.height,
    required this.totalOutputs,
    required this.tipHashHex,
  });

  @override
  int get hashCode =>
      height.hashCode ^ totalOutputs.hashCode ^ tipHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChainStatusResult &&
          runtimeType == other.runtimeType &&
          height == other.height &&
          totalOutputs == other.totalOutputs &&
          tipHashHex == other.tipHashHex;
}

/// Key pair information for a derived path.
class KeyPairInfo {
  final String address;
  final String viewPublicHex;
  final String spendPublicHex;
  final String ed25519PublicHex;
  final String wotsPublicHashHex;

  const KeyPairInfo({
    required this.address,
    required this.viewPublicHex,
    required this.spendPublicHex,
    required this.ed25519PublicHex,
    required this.wotsPublicHashHex,
  });

  @override
  int get hashCode =>
      address.hashCode ^
      viewPublicHex.hashCode ^
      spendPublicHex.hashCode ^
      ed25519PublicHex.hashCode ^
      wotsPublicHashHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPairInfo &&
          runtimeType == other.runtimeType &&
          address == other.address &&
          viewPublicHex == other.viewPublicHex &&
          spendPublicHex == other.spendPublicHex &&
          ed25519PublicHex == other.ed25519PublicHex &&
          wotsPublicHashHex == other.wotsPublicHashHex;
}

/// Hybrid signature result (Ed25519 + WOTS+).
class SignResult {
  final String ed25519SignatureHex;
  final String ed25519PublicHex;
  final String wotsSignatureHex;
  final String wotsPublicHashHex;
  final String wotsAddrSeedHex;

  const SignResult({
    required this.ed25519SignatureHex,
    required this.ed25519PublicHex,
    required this.wotsSignatureHex,
    required this.wotsPublicHashHex,
    required this.wotsAddrSeedHex,
  });

  @override
  int get hashCode =>
      ed25519SignatureHex.hashCode ^
      ed25519PublicHex.hashCode ^
      wotsSignatureHex.hashCode ^
      wotsPublicHashHex.hashCode ^
      wotsAddrSeedHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SignResult &&
          runtimeType == other.runtimeType &&
          ed25519SignatureHex == other.ed25519SignatureHex &&
          ed25519PublicHex == other.ed25519PublicHex &&
          wotsSignatureHex == other.wotsSignatureHex &&
          wotsPublicHashHex == other.wotsPublicHashHex &&
          wotsAddrSeedHex == other.wotsAddrSeedHex;
}

/// Result of a transaction send.
class TransactionSendResult {
  final String txHashHex;
  final bool accepted;
  final String errorMessage;
  final String spentIndicesCsv;

  const TransactionSendResult({
    required this.txHashHex,
    required this.accepted,
    required this.errorMessage,
    required this.spentIndicesCsv,
  });

  @override
  int get hashCode =>
      txHashHex.hashCode ^ accepted.hashCode ^ errorMessage.hashCode ^ spentIndicesCsv.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TransactionSendResult &&
          runtimeType == other.runtimeType &&
          txHashHex == other.txHashHex &&
          accepted == other.accepted &&
          errorMessage == other.errorMessage &&
          spentIndicesCsv == other.spentIndicesCsv;
}

/// Complete wallet creation result.
class WalletCreateResult {
  final String mnemonic;
  final String seedHex;
  final String addressMainnet;
  final String addressTestnet;
  final String viewPublicHex;
  final String spendPublicHex;

  const WalletCreateResult({
    required this.mnemonic,
    required this.seedHex,
    required this.addressMainnet,
    required this.addressTestnet,
    required this.viewPublicHex,
    required this.spendPublicHex,
  });

  @override
  int get hashCode =>
      mnemonic.hashCode ^
      seedHex.hashCode ^
      addressMainnet.hashCode ^
      addressTestnet.hashCode ^
      viewPublicHex.hashCode ^
      spendPublicHex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletCreateResult &&
          runtimeType == other.runtimeType &&
          mnemonic == other.mnemonic &&
          seedHex == other.seedHex &&
          addressMainnet == other.addressMainnet &&
          addressTestnet == other.addressTestnet &&
          viewPublicHex == other.viewPublicHex &&
          spendPublicHex == other.spendPublicHex;
}

/// Result of a wallet scan.
class WalletScanResult {
  final BigInt totalBalance;
  final BigInt outputCount;
  final BigInt scannedHeight;
  final String outputsJson;

  const WalletScanResult({
    required this.totalBalance,
    required this.outputCount,
    required this.scannedHeight,
    required this.outputsJson,
  });

  @override
  int get hashCode =>
      totalBalance.hashCode ^
      outputCount.hashCode ^
      scannedHeight.hashCode ^
      outputsJson.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WalletScanResult &&
          runtimeType == other.runtimeType &&
          totalBalance == other.totalBalance &&
          outputCount == other.outputCount &&
          scannedHeight == other.scannedHeight &&
          outputsJson == other.outputsJson;
}
